name: fluttersample
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  shared_preferences: ^0.5.6+2
  flutter_styled_toast: ^1.3.0
  badges: ^1.1.1
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true